### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/debug-ls#1]
```
$ ./debug-ls hello.ls 
Debugger listening on ws://127.0.0.1:9229/9a2f7768-6945-47af-b69f-96f3dec4c51e
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
xxxx/debugging-livescript/hello.ls:1
(function (exports, require, module, __filename, __dirname) { sleep = (f, ms) -> set-timeout ms, f
                                                                               ^

SyntaxError: Unexpected token >
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by ceremcem** [comment]
Maybe related with https://github.com/gkz/LiveScript/issues/830
