### ISSUE TITLE
Can not find browserify-livescript when project is used as a debugger tool

### ISSUE THREAD

**Issue by ceremcem** [ceremcem/debug-ls#3]
When this project is located in a subfolder and created a link to `debug-ls`, browserify throws the following error: 
```
Error: Cannot find module 'browserify-livescript' from '/path/to/myapp'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:47:17
    at process (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:174:43)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:189:17)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:70:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:93:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:23:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

# Workaround: 

Copy and paste `debugging-livescript/node_modules` folder into `/path/to/myapp`

**Comment by ceremcem** [comment]
Switched to rollup, which makes this issue invalid.
